#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys

if os.path.isdir(os.path.join(".", "src")) and os.path.isfile(
        os.path.join(".", "setup.py")):
    sys.path.append(os.path.realpath("src"))
    sys.path.append(os.path.realpath("src/agstoolbox"))

from agstoolbox.core.cmdline.cmdline import cmdline

if __name__ == '__main__':
    cmdline(True, 'atbx')


def main():
    cmdline(True, 'atbx')
