name: Windows .exe - Pyinstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: ericoporto/agstoolbox-pyinstaller-action@main
      with:
        exe_file: agstoolbox.exe
        exe_file_info: agstoolbox_version_info.txt
        spec: agstoolbox.spec
        path: .

    - name: Package Application
      uses: ericoporto/agstoolbox-pyinstaller-action@main
      with:
        exe_file: atbx.exe
        exe_file_info: atbx_version_info.txt
        spec: atbx.spec
        path: .

    - uses: actions/upload-artifact@v3
      with:
        name: agstoolbox
        path: ./dist/windows
